# Generated by Django 5.0 on 2023-12-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('patientid', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255, null=True)),
                ('MiddleName', models.CharField(max_length=255, null=True)),
                ('LastName', models.CharField(max_length=255, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('Occupation', models.CharField(max_length=255, null=True)),
                ('MaritialStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Pincode', models.CharField(max_length=20, null=True)),
                ('MobileNumber', models.CharField(max_length=20, null=True)),
                ('AlternateNumber', models.CharField(max_length=20, null=True)),
                ('EmailAddress', models.EmailField(max_length=255, null=True)),
                ('LandlineNumber', models.CharField(max_length=20, null=True)),
                ('EmergencyContactPersonFirstName', models.CharField(max_length=255, null=True)),
                ('EmergencyContactPersonLastName', models.CharField(max_length=255, null=True)),
                ('EmergencyContactPersonMobileNumber', models.CharField(max_length=20, null=True)),
                ('EmergencyContactPersonRelation', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
