# Generated by Django 5.0 on 2023-12-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='EmergencyContactPersonRelation',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Son', 'Son'), ('Daughter', 'Daughter')], max_length=100, null=True),
        ),
    ]
