# Generated by Django 5.0 on 2023-12-16 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0002_alter_basicinfo_emergencycontactpersonrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
