# Generated by Django 5.0 on 2023-12-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0003_basicinfo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalProfile',
            fields=[
                ('phy_profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patientid', models.IntegerField(null=True)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Appetite', models.CharField(choices=[('good', 'Good'), ('verygood', 'Very Good'), ('abnormally high', 'Abnormally High'), ('poor', 'Poor'), ('very poor', 'Very Poor'), ('absent', 'Absent')], max_length=50, null=True)),
                ('SleepCycle', models.CharField(choices=[('good', 'Good'), ('verygood', 'Very Good'), ('abnormally high', 'Abnormally High'), ('poor', 'Poor'), ('verypoor', 'Very Poor'), ('absent', 'Absent')], max_length=50, null=True)),
                ('FoodPreferences', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Lacto Vegetarian', 'Lacto Vegetarian'), ('Lact-ovo-Vegetarian', 'Lact-ovo-Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=50, null=True)),
                ('DigestiveIssues', models.CharField(choices=[('Constipation', 'Constipation'), ('Diarrhoea', 'Diarrhoea'), ('Bloating', 'Bloating'), ('Other', 'Other'), ('None', 'None')], max_length=50, null=True)),
                ('CuisinePreferred', models.CharField(choices=[('South Indian', 'South Indian'), ('North Indian', 'North Indian'), ('Asian', 'Asian'), ('East Indian', 'East Indian'), ('West Indian', 'West Indian'), ('Mediterranean', 'Mediterranean'), ('Western', 'Western'), ('Others', 'Others')], max_length=50, null=True)),
                ('Description1', models.CharField(choices=[('Cooking/eating at home mostly', 'Cooking/eating at home mostly'), ('Eating out/ordering food online atleast 2-3 times a week', 'Eating out/ordering food online atleast 2-3 times a week'), ('Eating out/ordering food online mostly', 'Eating out/ordering food online mostly')], max_length=100, null=True)),
                ('Description2', models.CharField(choices=[('I have a cook', 'I have a cook'), ('A family member/friend cooks for me', 'A family member/friend cooks for me'), ('I make my own food', 'I make my own food')], max_length=100, null=True)),
            ],
        ),
    ]
