# Generated by Django 5.0 on 2023-12-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0004_physicalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalprofile',
            name='patientid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo'),
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('med_profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('SupplementsTaken', models.CharField(choices=[('Multi-Vitamins', 'Multi-Vitamins'), ('Single Vitamins', 'Single Vitamins'), ('Herbs/herbal supplements', 'Herbs/herbal supplements'), ('Nutraceuticals', 'Nutraceuticals'), ('Protein supplements', 'Protein supplements')], max_length=50, null=True)),
                ('RecentIllnessOrInjury', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('ChronicMedicalConditions', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('DiagnosedWithChronicDiseases', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('RespiratorySymptoms', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('NeurologicalSymptoms', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('DrugAllergiesOrAdverseReactions', models.CharField(max_length=500, null=True)),
                ('patientid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo')),
            ],
        ),
    ]
