# Generated by Django 5.0 on 2023-12-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0005_alter_physicalprofile_patientid_medicalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitsInfo',
            fields=[
                ('hab_info_id', models.IntegerField(primary_key=True, serialize=False)),
                ('LevelOfActivity', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly active', 'Lightly active'), ('Moderately active', 'Moderately active'), ('Very active', 'Very active')], max_length=50, null=True)),
                ('SmokingHabit', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('AlcoholConsumption', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('CaffeineConsumption', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('TobaccoConsumption', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('OtherHabits', models.CharField(max_length=500, null=True)),
                ('patientid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo')),
            ],
        ),
    ]
