# Generated by Django 5.0 on 2023-12-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0006_habitsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitsinfo',
            name='patientid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo'),
            preserve_default=False,
        ),
    ]
