# Generated by Django 5.0 on 2023-12-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0011_remove_dietplan_patientid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalsTb',
            fields=[
                ('vitals_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Temperature', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('BP', models.CharField(choices=[('Systolic', 'Systolic'), ('Diastolic', 'Diastolic')], max_length=9, null=True)),
                ('GeneralBodyType', models.CharField(max_length=100, null=True)),
                ('PulseRate', models.IntegerField(null=True)),
                ('HeartRate', models.IntegerField(null=True)),
                ('SpO2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('PresentIllnessOnset', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
                ('SurgicalHistory', models.CharField(choices=[('emergency', 'emergency'), ('elective', 'elective')], max_length=9, null=True)),
                ('FamilyHistory', models.CharField(choices=[('maternal family', 'maternal family'), ('paternal family', 'paternal family')], max_length=16, null=True)),
                ('AddictionHabits', models.CharField(choices=[('alcohol', 'alcohol'), ('smoking', 'smoking'), ('tobacco', 'tobacco')], max_length=7, null=True)),
                ('MedicationHistoryMonth', models.IntegerField(null=True)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo')),
            ],
        ),
    ]
