# Generated by Django 5.0 on 2023-12-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0012_vitalstb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VitalsTb',
            new_name='Vitals',
        ),
    ]
