# Generated by Django 5.0 on 2023-12-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0014_pathology'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvPariksha',
            fields=[
                ('av_pariksha_id', models.IntegerField(primary_key=True, serialize=False)),
                ('StoolConsistency', models.CharField(choices=[('solid', 'solid'), ('semisolid', 'semisolid'), ('fluid', 'fluid')], max_length=10, null=True)),
                ('StoolOdour', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7, null=True)),
                ('StoolColour', models.CharField(max_length=50, null=True)),
                ('StoolQuantity', models.CharField(choices=[('more', 'more'), ('less', 'less')], max_length=4, null=True)),
                ('UrineVolume', models.CharField(max_length=20, null=True)),
                ('UrineTurbidity', models.CharField(max_length=20, null=True)),
                ('BurningPressure', models.CharField(max_length=20, null=True)),
                ('AbnormalColorOfUrine', models.CharField(max_length=50, null=True)),
                ('CoatingOnTheTongue', models.CharField(max_length=50, null=True)),
                ('FissuresOnTheTongue', models.CharField(max_length=50, null=True)),
                ('AbnormalColourOfTheTongue', models.CharField(max_length=50, null=True)),
                ('Sound', models.CharField(choices=[('normal', 'normal'), ('abnormal', 'abnormal')], max_length=8, null=True)),
                ('SoundHearingCapacity', models.CharField(max_length=50, null=True)),
                ('SoundSpeech', models.CharField(choices=[('low voice', 'low voice'), ('muffled voice', 'muffled voice'), ('high pitched voice', 'high pitched voice'), ('hoarse voice', 'hoarse voice')], max_length=18, null=True)),
                ('EyeMention', models.CharField(choices=[('normal', 'normal'), ('abnormal', 'abnormal')], max_length=8, null=True)),
                ('WhichEye', models.CharField(choices=[('left eye', 'left eye'), ('right eye', 'right eye')], max_length=10, null=True)),
                ('PalpebralConjunctiva', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('BulbarConjunctiva', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('UnderEyeSacks', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('UnderEyeBlackishsness', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('PeriorbitalSwelling', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('Appearance', models.CharField(choices=[('lean built', 'lean built'), ('moderate', 'moderate')], max_length=10, null=True)),
                ('MuscleSturdiness', models.CharField(choices=[('good', 'good'), ('moderate', 'moderate'), ('flabby', 'flabby')], max_length=8, null=True)),
                ('Spine', models.CharField(choices=[('erect', 'erect'), ('hunk back', 'hunk back')], max_length=9, null=True)),
                ('Face', models.CharField(choices=[('pale', 'pale'), ('dull', 'dull'), ('active', 'active'), ('charming', 'charming')], max_length=8, null=True)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo')),
            ],
        ),
    ]
