# Generated by Django 5.0 on 2023-12-23 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0015_avpariksha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Complaints', models.TextField(null=True)),
                ('Investigation_Findings', models.TextField(null=True)),
                ('Preliminary_Diagnosis', models.TextField(null=True)),
                ('Final_Diagnosis', models.TextField(null=True)),
                ('Investigations_Advised', models.TextField(null=True)),
                ('Date_of_Next_Visit', models.DateField(null=True)),
                ('DietDos', models.TextField(null=True)),
                ('DietDont', models.TextField(null=True)),
                ('Life_Style_Dos', models.TextField(null=True)),
                ('Life_Style_Dont', models.TextField(null=True)),
                ('Yoga_Pranayam_Exercise_Dos', models.TextField(null=True)),
                ('Yoga_Pranayam_Exercise_Dont', models.TextField(null=True)),
                ('Additional_Notes', models.TextField(null=True)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDose',
            fields=[
                ('prescriptiondose_id', models.IntegerField(primary_key=True, serialize=False)),
                ('SerialNo', models.IntegerField(null=True)),
                ('MedName', models.CharField(max_length=255, null=True)),
                ('Dose', models.CharField(max_length=50, null=True)),
                ('Timing', models.CharField(max_length=50, null=True)),
                ('Frequency', models.CharField(max_length=50, null=True)),
                ('RelationWithFood', models.CharField(max_length=50, null=True)),
                ('Duration', models.CharField(max_length=50, null=True)),
                ('Adjuvant', models.CharField(max_length=50, null=True)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitasana.prescription')),
            ],
        ),
    ]
