# Generated by Django 5.0 on 2023-12-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0017_dietplan_nutritionaladv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalprofile',
            name='FoodPreferences',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
