# Generated by Django 5.0 on 2023-12-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0019_alter_physicalprofile_cuisinepreferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitsinfo',
            name='LevelOfActivity',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='DrugAllergiesOrAdverseReactions',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='SupplementsTaken',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
