# Generated by Django 5.0 on 2023-12-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0020_alter_habitsinfo_levelofactivity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriptionDose',
        ),
    ]
