# Generated by Django 5.0 on 2023-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0021_delete_prescriptiondose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='ChronicMedicalConditions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='DiagnosedWithChronicDiseases',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='DrugAllergiesOrAdverseReactions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='NeurologicalSymptoms',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='RecentIllnessOrInjury',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='RespiratorySymptoms',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='Appetite',
            field=models.CharField(choices=[('Good', 'Good'), ('Very Good', 'Very Good'), ('Abnormally High', 'Abnormally High'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor'), ('Absent', 'Absent')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='SleepCycle',
            field=models.CharField(choices=[('Good', 'Good'), ('Very Good', 'Very Good'), ('Abnormally High', 'Abnormally High'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor'), ('Absent', 'Absent')], max_length=50, null=True),
        ),
    ]
