# Generated by Django 5.0 on 2023-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0022_alter_medicalprofile_chronicmedicalconditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitsinfo',
            name='CigarettesPerDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitsinfo',
            name='YearsOfSmoking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitsinfo',
            name='AlcoholConsumption',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='habitsinfo',
            name='CaffeineConsumption',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='habitsinfo',
            name='SmokingHabit',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='habitsinfo',
            name='TobaccoConsumption',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='ChronicMedicalConditions',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='DiagnosedWithChronicDiseases',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='DrugAllergiesOrAdverseReactions',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='NeurologicalSymptoms',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='RecentIllnessOrInjury',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='RespiratorySymptoms',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='Appetite',
            field=models.CharField(choices=[('good', 'Good'), ('verygood', 'Very Good'), ('abnormally high', 'Abnormally High'), ('poor', 'Poor'), ('very poor', 'Very Poor'), ('absent', 'Absent')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='SleepCycle',
            field=models.CharField(choices=[('good', 'Good'), ('verygood', 'Very Good'), ('abnormally high', 'Abnormally High'), ('poor', 'Poor'), ('verypoor', 'Very Poor'), ('absent', 'Absent')], max_length=50, null=True),
        ),
    ]
