# Generated by Django 5.0 on 2023-12-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0023_habitsinfo_cigarettesperday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitsinfo',
            name='CigarettesPerDay',
        ),
        migrations.RemoveField(
            model_name='habitsinfo',
            name='YearsOfSmoking',
        ),
    ]
