# Generated by Django 5.0 on 2023-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0024_remove_habitsinfo_cigarettesperday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitsinfo',
            name='DrinksPerDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitsinfo',
            name='YearsOfDrinking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
