# Generated by Django 5.0 on 2023-12-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0026_remove_habitsinfo_drinksperday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitsinfo',
            name='CigarettesPerDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitsinfo',
            name='DrinksPerDay_Alcohol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitsinfo',
            name='NumberOfCupsPerDay_Caffeine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitsinfo',
            name='TimesPerDay_Tobacco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitsinfo',
            name='YearsOfDrinking_Alcohol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitsinfo',
            name='YearsOfDrinking_Caffeine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitsinfo',
            name='YearsOfSmoking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
