# Generated by Django 5.0 on 2023-12-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0027_habitsinfo_cigarettesperday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutritionalAdv',
        ),
    ]
