# Generated by Django 5.0 on 2023-12-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0028_delete_nutritionaladv'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='Dietician',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='FRIDAY_MEAL1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='FRIDAY_MEAL2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='FRIDAY_MEAL3',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='FRIDAY_MEAL4',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='FRIDAY_MEAL5',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='FRIDAY_MEAL6',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='MONDAY_MEAL1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='MONDAY_MEAL2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='MONDAY_MEAL3',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='MONDAY_MEAL4',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='MONDAY_MEAL5',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='MONDAY_MEAL6',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SATURDAY_MEAL1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SATURDAY_MEAL2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SATURDAY_MEAL3',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SATURDAY_MEAL4',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SATURDAY_MEAL5',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SATURDAY_MEAL6',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SUNDAY_MEAL1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SUNDAY_MEAL2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SUNDAY_MEAL3',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SUNDAY_MEAL4',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SUNDAY_MEAL5',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SUNDAY_MEAL6',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='THURSDAY_MEAL1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='THURSDAY_MEAL2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='THURSDAY_MEAL3',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='THURSDAY_MEAL4',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='THURSDAY_MEAL5',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='THURSDAY_MEAL6',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='TUESDAY_MEAL1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='TUESDAY_MEAL2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='TUESDAY_MEAL3',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='TUESDAY_MEAL4',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='TUESDAY_MEAL5',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='TUESDAY_MEAL6',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='WEDNESDAY_MEAL1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='WEDNESDAY_MEAL2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='WEDNESDAY_MEAL3',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='WEDNESDAY_MEAL4',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='WEDNESDAY_MEAL5',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='WEDNESDAY_MEAL6',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
