# Generated by Django 5.0 on 2023-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0031_alter_dietplan_meal1_alter_dietplan_meal2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='MEAL1',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='MEAL2',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='MEAL3',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='MEAL4',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='MEAL5',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='MEAL6',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='FRI_MEAL',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='MON_MEAL',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SAT_MEAL',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='SUN_MEAL',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='THU_MEAL',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='TUE_MEAL',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='WED_MEAL',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
