# Generated by Django 5.0 on 2023-12-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0032_remove_dietplan_meal1_remove_dietplan_meal2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='FRI_MEAL',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='MON_MEAL',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='SAT_MEAL',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='SUN_MEAL',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='THU_MEAL',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='TUE_MEAL',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='WED_MEAL',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
