# Generated by Django 5.0 on 2023-12-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0033_alter_dietplan_fri_meal_alter_dietplan_mon_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDose',
            fields=[
                ('prescriptiondose_id', models.IntegerField(primary_key=True, serialize=False)),
                ('SerialNo', models.IntegerField(null=True)),
                ('MedName', models.CharField(max_length=255, null=True)),
                ('Dose', models.CharField(max_length=50, null=True)),
                ('Timing', models.CharField(max_length=50, null=True)),
                ('Frequency', models.CharField(max_length=50, null=True)),
                ('RelationWithFood', models.CharField(max_length=50, null=True)),
                ('Duration', models.CharField(max_length=50, null=True)),
                ('Adjuvant', models.CharField(max_length=50, null=True)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitasana.basicinfo')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitasana.prescription')),
            ],
        ),
    ]
