# Generated by Django 5.0 on 2023-12-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0034_prescriptiondose'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='Adjuvant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Dose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Frequency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='MedName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='RelationWithFood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Timing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PrescriptionDose',
        ),
    ]
