# Generated by Django 5.0 on 2023-12-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0035_prescription_adjuvant_prescription_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='patientid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
