# Generated by Django 5.0 on 2023-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0036_alter_basicinfo_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avpariksha',
            name='av_pariksha_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basicinfoop',
            name='BasicInfoOpID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='dietplan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='habitsinfo',
            name='hab_info_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='med_profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='pathology_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='phy_profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vitals_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
