# Generated by Django 5.0 on 2024-01-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0039_personaldetails_dosa_physicalchar_dosa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalprofile',
            name='CuisinePreferred',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='Description1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='Description2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='DigestiveIssues',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='FoodPreferences',
            field=models.TextField(null=True),
        ),
    ]
