# Generated by Django 5.0 on 2024-01-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0040_alter_physicalprofile_cuisinepreferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitsinfo',
            name='LevelOfActivity',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='SupplementsTaken',
            field=models.TextField(null=True),
        ),
    ]
