# Generated by Django 5.0 on 2024-01-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0041_alter_habitsinfo_levelofactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalprofile',
            name='FoodPreferences',
            field=models.JSONField(null=True),
        ),
    ]
