# Generated by Django 5.0 on 2024-01-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0042_alter_physicalprofile_foodpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalprofile',
            name='CuisinePreferred',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='Description1',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='Description2',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalprofile',
            name='DigestiveIssues',
            field=models.JSONField(null=True),
        ),
    ]
