# Generated by Django 5.0 on 2024-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0048_alter_personaldetails_dosa_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='SupplementsTaken',
            field=models.JSONField(null=True),
        ),
    ]
