# Generated by Django 5.0 on 2024-01-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0050_alter_medicalprofile_supplementstaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='SupplementsTaken',
            field=models.JSONField(null=True),
        ),
    ]
