# Generated by Django 5.0 on 2024-01-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0051_alter_medicalprofile_supplementstaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='ChronicMedicalConditions_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='DiagnosedWithChronicDiseases_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='DrugAllergiesOrAdverseReactions_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='NeurologicalSymptoms_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='RecentIllnessOrInjury_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='RespiratorySymptoms_details',
            field=models.TextField(null=True),
        ),
    ]
