# Generated by Django 5.0 on 2024-01-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitasana', '0052_medicalprofile_chronicmedicalconditions_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitsinfo',
            name='LevelOfActivity',
            field=models.JSONField(null=True),
        ),
    ]
